### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Y-Less** [openmultiplayer/open.mp#534]
A list of things to get done for a target of a Christmas release.  Proposed (admittedly short) timeline:

* 19/12/22 (Monday) - Feature and merge freeze.
* 20/12/22-24/12/22 - Documentation and testing.
* 25/12/22 - Release.

Before Monday:

* [x] Re-rebase and re-review recent master changes.
* [x] #533 
* [x] #528 
* [x] #522 
* [x] #499 - This is in draft, and merging might not be feasible.
* [x] #453 - Also in draft, status @AmyrAhmady?

After Monday:

* [x] Put together a complete download package - server, editor, includes, basic readmes, etc.
* [x] Prepare an announcement.
* [x] Forums (if recent events have proven anything it is that a single linear intermixed chat system is terrible for communication).
* [x] Any outstanding blocking bugs?
* [x] SDK/components documentation.
* [x] Ensure our plugins are updated.

Anything else?
